CREATE TABLE BOOK
(
	ID BIGINT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	AUTHOR VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);


INSERT INTO OWNER (ID, NAME, BIRTH_DATE)
VALUES(1, 'John', CURRENT_DATE());
INSERT INTO OWNER (ID, NAME, BIRTH_DATE)
VALUES(2, 'Ryan', CURRENT_DATE());
INSERT INTO OWNER (ID, NAME, BIRTH_DATE)
VALUES(3, 'Chris', CURRENT_DATE());